name: CI
on:
  push:
    branches:
      - 0.8.5-ss
    tags:
      - v*
  pull_request:
    branches:
      - 0.8.5-ss

jobs:
  check_wrapper:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Release APK
        run: ./gradlew assembleStandardRelease --stacktrace

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/standard/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}


      - name: Create Release
        uses: actions/upload-artifact@v2
        with:
          name: Tachiyomi-Standard-Release
          path: ${{ env.SIGNED_RELEASE_FILE }}

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: Tachiyomi-Standard-Release
